### ISSUE TITLE
"db_name must be a string or symbol" on rake assets:precompile

### ISSUE THREAD

**Issue by mickaelmagniez** [RailsApps/rails3-mongoid-devise#9]
Thank you for those amazing tutorials.

I run into an issue when i try to exec the rake task "assets:precompile" on non modified code.

This is the trace : 

```
$ rake --trace assets:precompile
** Invoke assets:precompile (first_time)
** Execute assets:precompile
rake aborted!
db_name must be a string or symbol

Tasks: TOP => environment
```

Thanks,

Mickael.

**Comment by DanielKehoe** [comment]
I've reproduced this issue. As far as I can see, it is not intrinsic to the example app. I suspect you will see the same error with other apps that use Mongoid. To verify that, I suggest you create a very simple app that uses Mongoid. If you find that `assets:precompile` does not work when you are using Mongoid with a simple test app, please ask for assistance on the Mongoid mailing list.

I will leave this issue open and if you obtain more information, I would very much appreciate it if you could update the issue here with further information.

--- Daniel

**Comment by mickaelmagniez** [comment]
Thanks for the response.

This is the answer from Nick Hoffman : 

"When Mongoid reads its config file, Rails thinks that we're dealing with the production environment. How strange!

Thus, Mongoid reads the production settings from config/mongoid.yml , which rely on environment variables (that don't exist at that time) to define the DB name, host, port, etc.

A workaround is to specify the Rails environment on the CLI. Eg:

```
RAILS_ENV=development rake assets:precompile
```

To be honest, I don't think there's anything that we can do for this problem within Mongoid. Rails needs to fix which environment it reports."

**Comment by DanielKehoe** [comment]
Thanks for providing the information.

-- Daniel

**Comment by otobrglez** [comment]
I got the same problem if I used following code inside my model definition.

```
Mongoid.autocreate_indexes = true
```
